sudo: required
notifications:
  email:
    recipients:
      - hatohol-commit@lists.sourceforge.net
language: cpp
compiler:
  - gcc
  - clang
env:
  global:
    - MLPL_LOGGER_LEVEL=WARN
    - NO_MAKE=yes
    - TEST_AMQP_URL="amqp://test_user:test_password@localhost:5673/test"
  matrix:
    - RUN_TEST="test/run-server-test.sh"
matrix:
  include:
    - compiler: gcc
      env: RUN_TEST="test/dist-check.sh"
    - compiler: gcc
      env: RUN_TEST="test/run-client-test.sh"
    - compiler: gcc
      env: RUN_TEST="test/feature-test.sh"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.8-dev
      - g++-4.8
      - autotools-dev
      - libglib2.0-dev
      - libsoup2.4-dev
      - libmysqlclient-dev
      - sqlite3
      - uuid-dev
      - python-pip
      - expect
      - python-dev
      - rabbitmq-server

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  # These pacakges aren't approved by apt addon of Travis.
  # See also: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
  - sudo apt-get install -qq -y libjson-glib-dev ndoutils-nagios3-mysql npm libq pidmessaging2-dev libqpidtypes1-dev libqpidcommon2-dev qpidd python-pika
  - server/misc/setup-cutter.sh
  - server/misc/setup-librabbitmq-ppa.sh
  - sudo sh -c "printf '[%s]\n%s=%s\n' mysqld character-set-server utf8  > /etc/mysql/conf.d/utf8.cnf"
  - sudo sh -c "printf '[%s]\n%s=%s\n' client default-character-set utf8  >> /etc/mysql/conf.d/utf8.cnf"
  - mysql -u root < data/test/setup.sql
  - npm install
  - sudo pip install django==1.5.4
  - sudo pip install mysql-python
  - sudo pip install daemon
  - sudo sh -c "echo acl allow all all > /etc/qpid/qpidd.acl"
  - sudo /etc/init.d/qpidd restart
  - sudo server/misc/setup-rabbitmq-server-port.sh
  - sudo service rabbitmq-server restart
before_script:
  - ./autogen.sh
  - ./configure
  - make
  - sudo chmod +r /var/log/syslog
  - sudo chmod 777 /var/run
script:
  - echo $RUN_TEST; eval "$RUN_TEST"
